<?php

require_once(__DIR__ . '/../includes/fpdf/fpdf.php');
require_once(__DIR__ . '/../config.php');

if (!isset($_GET['device_id']) || empty($_GET['device_id'])) {
    die("Invalid device ID");
}

$device_id = (int) $_GET['device_id'];

$stmt = $conn->prepare("SELECT * FROM devices WHERE device_id = ?");
$stmt->bind_param("i", $device_id);
$stmt->execute();

$result = $stmt->get_result();

if ($result->num_rows === 0) {
    die("Device not found");
}

$device = $result->fetch_assoc();

$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetAutoPageBreak(true, 20);

// Header
$pdf->SetFont('Arial', 'B', 20);
$pdf->Cell(190, 20, 'Device Details Report', 0, 1, 'C');

$pdf->SetFont('Arial', 'B', 12);
$pdf->SetTextColor(100, 100, 100);
$pdf->Cell(190, 8, 'Generated on: ' . date('Y-m-d H:i:s'), 0, 1, 'C');

$pdf->Ln(10);

// Device Title
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('Arial', 'B', 18);
$pdf->MultiCell(190, 10, $device['device_name'], 0, 'C');

$pdf->Ln(8);

//Device Image
$deviceImage = trim($device['device_image'] ?? '');

if (!empty($deviceImage)) {

    // Full path
    $imagePath = __DIR__ . '/deviceimages/' . basename($deviceImage);

    if (file_exists($imagePath) && is_readable($imagePath)) {

        // Detect REAL mime type
        $imageInfo = getimagesize($imagePath);

        if ($imageInfo !== false) {

            $mime = $imageInfo['mime'];

            // Supported formats
            $allowedMime = ['image/jpeg', 'image/png', 'image/webp', 'image/jpg'];

            if (in_array($mime, $allowedMime)) {

                $originalWidth  = $imageInfo[0];
                $originalHeight = $imageInfo[1];

                $maxWidth  = 70;
                $maxHeight = 70;

                // Maintain aspect ratio
                $ratio = min($maxWidth / $originalWidth, $maxHeight / $originalHeight);

                $newWidth  = $originalWidth * $ratio;
                $newHeight = $originalHeight * $ratio;

                // Center image
                $x = ($pdf->GetPageWidth() - $newWidth) / 2;
                $y = $pdf->GetY();

                // Render image
                $pdf->Image($imagePath, $x, $y, $newWidth, $newHeight);
                $pdf->SetY($y + $newHeight + 10);
            } else {
                $pdf->SetFont('Arial', 'I', 11);
                $pdf->SetTextColor(200, 0, 0);
                $pdf->Cell(190, 10, 'Unsupported image format. Only JPG and PNG allowed.', 0, 1, 'C');
                $pdf->Ln(5);
            }

        } else {
            $pdf->SetFont('Arial', 'I', 11);
            $pdf->SetTextColor(200, 0, 0);
            $pdf->Cell(190, 10, 'Invalid image file.', 0, 1, 'C');
            $pdf->Ln(5);
        }
    } else {
        $pdf->SetFont('Arial', 'I', 11);
        $pdf->SetTextColor(150, 150, 150);
        $pdf->Cell(190, 10, 'Image file not found.', 0, 1, 'C');
        $pdf->Ln(5);
    }
} else {
    $pdf->SetFont('Arial', 'I', 11);
    $pdf->SetTextColor(150, 150, 150);
    $pdf->Cell(190, 10, 'No image available.', 0, 1, 'C');
    $pdf->Ln(5);
}

// Product Info
function addRow($pdf, $label, $value)
{
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->Cell(55, 10, $label, 1);

    $pdf->SetFont('Arial', '', 12);
    $pdf->Cell(135, 10, $value, 1);

    $pdf->Ln();
}

addRow($pdf, 'Device ID', $device['device_id']);
addRow($pdf, 'Device Type', $device['device_type'] ?? 'N/A');
addRow($pdf, 'Price', 'RM ' . number_format($device['device_price'], 2));
addRow($pdf, 'Created At', $device['created_at'] ?? 'N/A');

$pdf->Ln(10);

// Description Section
$pdf->SetFont('Arial', 'B', 14);

$pdf->Cell(190, 10, 'Device Specification', 0, 1);
$pdf->SetFont('Arial', '', 12);
$pdf->MultiCell(190, 8, $device['device_specs'] ?? 'No description available.');

$pdf->Ln(10);

// Footer Note
$pdf->SetFont('Arial', 'I', 10);
$pdf->SetTextColor(120, 120, 120);

$pdf->MultiCell(190, 6, 'This document was automatically generated by the TechBridge Inventory Management System.');

// OUTPUT PDF
$pdf->Output('D', 'device_' . $device['device_id'] . '.pdf');

exit;